### PR TITLE
Detect duplicate items in the cart and increment quantities

### PR DESCRIPTION
**Pull request by shipleyr**

### CODE REVIEW

**Comment by shipleyr** [comment]
@Xerkus @nclundsten @EvanDotPro Can I request this gets merged please? This and #10 please.

**Comment by nclundsten** [comment]
what happens when they have different specials applied to a certain
quantity?

Nigel

**Comment by shipleyr** [comment]
@nclundsten This PR has been open since April (8 months) asking for comments and suggestions and now it has been merged you have a problem with it? Has development in Speck kicked off again from your end?

Without this each time you add an item from catalog into your cart it adds another cart line item of the same product. I'd suggest that the behavior this PR adds is the norm (by finding matching items already in the basket and increment its quantity) and If you want to give special offers based on discounts I'd suggest that this is a special case and you need another module to handle things like that. Hook the add event and deal with it there. We have created a SpeckCartVoucher module for handling exactly this kind of eventuality - It looks for specific items added to the cart and applies a voucher discount into the cart item. This module could easily be extended to perform the behavior you are suggesting.

**Comment by nclundsten** [comment]
It was originally that way to accommodate old folks shopping medical
supplies. Leaving the cart in more of a historical view.  And it's not that
I have a problem with the change, as long as it can accommodate same item,
different price scenarios.

**Comment by nclundsten** [comment]
Development is not moving and I'd say it's stalled indefinitely, at least
as far as the project that originally prompted the creation of
speckcommerce.

**Pull request merged**
